package com.bunbeauty.ideal.myapplication.clean_architecture.callback.subscribers.service_comment

import com.bunbeauty.ideal.myapplication.clean_architecture.callback.subscribers.base_subscribers.BaseUpdateCallback
import com.bunbeauty.ideal.myapplication.clean_architecture.data.db.models.entity.comment.ServiceComment

interface UpdateServiceCommentCallback : BaseUpdateCallback<ServiceComment>