package com.bunbeauty.ideal.myapplication.cleanArchitecture.callback.subscribers.subscriber

import com.bunbeauty.ideal.myapplication.cleanArchitecture.callback.subscribers.baseSubscribers.BaseInsertCallback
import com.bunbeauty.ideal.myapplication.cleanArchitecture.data.db.models.entity.Subscriber

interface InsertSubscriberCallback:BaseInsertCallback<Subscriber>