package com.bunbeauty.ideal.myapplication.clean_architecture.callback.subscribers.subscriber

import com.bunbeauty.ideal.myapplication.clean_architecture.callback.subscribers.base_subscribers.BaseInsertCallback
import com.bunbeauty.ideal.myapplication.clean_architecture.data.db.models.entity.Subscriber

interface InsertSubscriberCallback:BaseInsertCallback<Subscriber>