package com.bunbeauty.ideal.myapplication.cleanArchitecture.callback.subscribers.serviceComment

import com.bunbeauty.ideal.myapplication.cleanArchitecture.callback.subscribers.baseSubscribers.BaseDeleteCallback
import com.bunbeauty.ideal.myapplication.cleanArchitecture.data.db.models.entity.comment.ServiceComment

interface DeleteServiceCommentCallback : BaseDeleteCallback<ServiceComment>