package com.bunbeauty.ideal.myapplication.cleanArchitecture.callback.subscribers.serviceComment

import com.bunbeauty.ideal.myapplication.cleanArchitecture.callback.subscribers.baseSubscribers.BaseInsertCallback
import com.bunbeauty.ideal.myapplication.cleanArchitecture.data.db.models.entity.comment.ServiceComment

interface InsertServiceCommentCallback : BaseInsertCallback<ServiceComment>