package com.bunbeauty.ideal.myapplication.cleanArchitecture.callback.subscribers.serviceComment

import com.bunbeauty.ideal.myapplication.cleanArchitecture.callback.subscribers.baseSubscribers.BaseGetListCallback
import com.bunbeauty.ideal.myapplication.cleanArchitecture.data.db.models.entity.comment.ServiceComment

interface ServiceCommentsCallback : BaseGetListCallback<ServiceComment>