package com.bunbeauty.ideal.myapplication.cleanArchitecture.callback.subscribers.subscription

import com.bunbeauty.ideal.myapplication.cleanArchitecture.callback.subscribers.baseSubscribers.BaseDeleteCallback
import com.bunbeauty.ideal.myapplication.cleanArchitecture.data.db.models.entity.Subscription

interface DeleteSubscriptionCallback:BaseDeleteCallback<Subscription>