package com.bunbeauty.ideal.myapplication.cleanArchitecture.callback.subscribers.subscription

import com.bunbeauty.ideal.myapplication.cleanArchitecture.callback.subscribers.baseSubscribers.BaseInsertCallback
import com.bunbeauty.ideal.myapplication.cleanArchitecture.data.db.models.entity.Subscription

interface InsertSubscriptionCallback:BaseInsertCallback<Subscription>